spring:
  application:
    name: flash-sale-ticketing
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flashsale}
    username: ${SPRING_DATASOURCE_USERNAME:flashsale}
    password: ${SPRING_DATASOURCE_PASSWORD:flashsale}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  # naive | pessimistic | optimistic | redis
  reserve-strategy: ${RESERVE_STRATEGY:redis}
  event-cache-ttl-seconds: 60
  # false = consumer không start -> message nằm chờ trong queue (demo Ngày 4)
  consumer-enabled: ${CONSUMER_ENABLED:true}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
